CREATE DATABASE music;
GRANT ALL PRIVILEGES ON DATABASE music TO app;
-- connect to the newly created database
\c music
CREATE TABLE T_BAND (ID SERIAL PRIMARY KEY, NAME VARCHAR(400) NOT NULL);

CREATE TABLE T_EVENT (ID SERIAL PRIMARY KEY, 
	NAME VARCHAR(100) NOT NULL, 
	DATE_START TIMESTAMP, 
	DATE_END TIMESTAMP);

CREATE TABLE T_EVENT_PLAN (ID SERIAL PRIMARY KEY, 
	EVENT_ID INTEGER REFERENCES T_EVENT ON DELETE CASCADE, 
	BAND_ID INTEGER REFERENCES T_BAND ON DELETE CASCADE,
	ORDER_NUM SMALLINT NOT NULL,
	START_TIME TIMESTAMP,
	END_TIME TIMESTAMP);
	
CREATE TABLE T_PERSON (ID SERIAL PRIMARY KEY, 
	NAME VARCHAR(25) NOT NULL, 
	SURNAME VARCHAR(50) NOT NULL, 
	BIRTH_DATE DATE NOT NULL, 
	NICKNAME VARCHAR(25));
	
CREATE TABLE T_PERSON_BAND_LINK (ID SERIAL PRIMARY KEY, 
	PERSON_ID INTEGER REFERENCES T_PERSON ON DELETE CASCADE, 
	BAND_ID INTEGER REFERENCES T_BAND ON DELETE CASCADE);


