CREATE TABLE T_EVENT_PLAN (ID SERIAL PRIMARY KEY, 
	EVENT_ID INTEGER REFERENCES T_EVENT ON DELETE CASCADE, 
	BAND_ID INTEGER REFERENCES T_BAND ON DELETE CASCADE,
	ORDER_NUM SMALLINT NOT NULL,
	START_TIME TIMESTAMP,
	END_TIME TIMESTAMP);